name: No Deploy (Test and Build)

on:
  # Run on pull requests targeting main
  pull_request:
    branches: [main]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.0-beta.5

      - name: Run Biome
        run: npx biome ci . --config-path config/biome.jsonc

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: config/.nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deep Type check
        run: npm run check:typescript

      - name: Run Astro Check
        run: npm run check:astro

      - name: Read Terraform version
        id: tf_version
        run: echo "version=$(cat config/.terraform-version | tr -d ' \n')" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: Run Terraform Validation
        run: npm run check:terraform

      - name: Test
        run: npm run test

      - name: Build application
        run: npm run build
