name: No Deploy (Test and Build)

on:
  # Run on any push to any branch except main
  push:
    branches-ignore: [main]

  # Run on any pull request targeting main
  pull_request:
    branches: [main]

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --prod
      - name: Lint
        run: pnpm run lint
      - name: Deep Type check
        run: pnpm run type-check
      - name: Run Astro Check
        run: pnpm run astro check
      - name: Build application
        run: pnpm run build
