name: No Deploy (Test and Build)

on:
  pull_request:

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.6

      - name: Run Biome
        run: biome ci .

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Deep Type check
        run: npm run check:ts

      - name: Test
        run: npm run test:unit

      - name: Build application
        run: npm run build
