name: No Deploy (Test and Build)

on:
  pull_request:

jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.0.6

      - name: Run Biome
        run: npx biome ci .

      - name: Setup Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Deep Type check
        run: npm run check:ts

      - name: Read Terraform version
        id: tf_version
        run: echo "version=$(cat .terraform-version | tr -d ' \n')" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: Run Terraform Validation
        run: npm run check:iac

      - name: Test
        run: npm run test:unit

      - name: Build application
        run: npm run build
